# Site settings
title: Matjaž Grillo
description: Personal portfolio
baseurl: "avtokozmetika-diamond" # the subpath of your site, e.g. /blog
url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Matjaž Grillo
user_description: I\'m always searching for the next challenge; no task is too scary nor too difficult. Lately I have been immersed in the <b>BIG FORMAT</b> printing, working for Copigraf.
user_title: s
email: matjaz.grillo@gmail.com
# twitter_username: lorem_ipsum
# github_username:  lorem_ipsum
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
